version: '3.8'

services:
  nan_spacex:
    container_name: nan_spacex
    build: ./server/
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      APP_PORT : 8000
      APP_VERSION : '1.0'
    networks:
      - nan

networks:
  nan:

